number = int(input('Type an integer number: '))

print(f'{number} X {1:2} = {number * 1}')
print(f'{number} X {2:2} = {number * 2}')
print(f'{number} X {3:2} = {number * 3}')
print(f'{number} X {4:2} = {number * 4}')
print(f'{number} X {5:2} = {number * 5}')
print(f'{number} X {6:2} = {number * 6}')
print(f'{number} X {7:2} = {number * 7}')
print(f'{number} X {8:2} = {number * 8}')
print(f'{number} X {9:2} = {number * 9}')
print(f'{number} X {10:2} = {number * 10}')
