some_text = input('Type something: ')
print(f'What\'s the primitive type of {some_text}? Is {type(some_text)}.')
print(f'This variable has only spaces? {some_text.isspace()}')
print(f'Is {some_text} numeric? {some_text.isnumeric()}')
print(f'Is {some_text} alphabetic? {some_text.isalpha()}')
print(f'Is {some_text} alphanumeric? {some_text.isalnum()}')
print(f'Is {some_text} uppercase? {some_text.isupper()}')
print(f'Is {some_text} lowercase? {some_text.islower()}')
print(f'Is {some_text} capitalized? {some_text.istitle()}')
